version: "3.7"

services:
  php-apache:
    container_name: "symfony-php-apache"
    build: ./docker/php-apache
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "80:80"

  db:
    container_name: "symfony-db"
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=symfony
      - MARIADB_USER=symfony
      - MARIADB_PASSWORD=symfony
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    container_name: "symfony-adminer"
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db-data:
