controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check

api_register:
    path: /api/register
    controller: App\Controller\RegistrationController::register
    methods: POST

api_user:
    path: /api/user
    controller: App\Controller\UserController::getCurrentUser
    methods: GET